# Generated by Django 5.0.3 on 2024-03-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guest',
            old_name='modile',
            new_name='mobile',
        ),
    ]
